# Generated by Django 5.1.7 on 2025-05-15 17:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='artist',
            name='instrument',
        ),
        migrations.AddField(
            model_name='artist',
            name='instruments',
            field=models.JSONField(default=list),
        ),
    ]
