# Generated by Django 5.1.7 on 2025-05-17 05:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0002_remove_artist_instrument_artist_instruments'),
    ]

    operations = [
        migrations.AddField(
            model_name='site',
            name='verified',
            field=models.BooleanField(default=False),
        ),
    ]
